### ISSUE TITLE
Serial printing of badges with names and data

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-artwork#2]
Some info is available here:
https://helpx.adobe.com/illustrator/using/data-driven-graphics-templates-variables.html

How to do it with Inkscape or Gimp?

**Comment by 0x48piraj** [comment]
Can't we use a Python Script to generate badges with serial names @mariobehling ?

**Comment by mariobehling** [comment]
We already have the Badgeyay project. The goal of this issue to get an answer to this question.
